Modified get/set json smart fields
servicetitan/RadaeePDF-Cordova pull request #1
Opened 2017-12-02 05:52 UTC by psonawane-servicetitan

2017-12-02 06:00 UTC, MaratFaskhiev requested changes

2017-12-02 06:00 UTC, MaratFaskhiev commented on src/android/ViewLib/src/main/java/com/radaee/util/RadaeePDFManager.java
> +                    for(int j = 0 ; j < mPage.GetAnnotCount() ; j++) {
`for (`

2017-12-02 06:00 UTC, MaratFaskhiev commented on src/android/ViewLib/src/main/java/com/radaee/util/RadaeePDFManager.java
> +                        if(mAnnotation != null && (mAnnotation.GetType() == 20 || mAnnotation.GetType() == 3)) {
1. `if (`
2. It would be better to add constants for 20 and 3

2017-12-02 06:00 UTC, MaratFaskhiev commented on src/android/ViewLib/src/main/java/com/radaee/util/RadaeePDFManager.java
> +                    if(mPagesAnnot.length() > 0) {
`if (`

2017-12-02 06:00 UTC, MaratFaskhiev commented on src/android/ViewLib/src/main/java/com/radaee/util/RadaeePDFManager.java
> +            if(mPages.length() > 0) {
`if (`

2017-12-02 06:00 UTC, MaratFaskhiev commented on src/android/ViewLib/src/main/java/com/radaee/util/RadaeePDFManager.java
> +        if(mPageJson.length() > 0) {
`if (`

2017-12-05 04:08 UTC, kanoshin approved these changes

2017-12-05 18:31 UTC, kanoshin commented on src/ios/Modules/FormManager/RDFormManager.m
> +            if (getEditTextOnly) {
Why there is no else block?

2017-12-05 18:32 UTC, kanoshin commented on src/ios/Modules/FormManager/RDFormManager.m
> +            if (getEditTextOnly) {
Oh, sorry, just noticed it. Indentation is hard here :).

2017-12-06 04:14 UTC, MaratFaskhiev approved these changes

2017-12-06 04:14 UTC, merged